language: python

python: 
  - 3.6

env:
  global:
  - PGPORT=5435

virtualenv:
  system_site_packages: true

addons:
   postgresql: "9.5"
   apt:
     packages:
     - postgresql-9.5-postgis-2.3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install binutils libproj-dev gdal-bin python-gdal

install:
  - pip install -r backend/requirements.txt

script: 
  - python backend/manage.py test WaldmeisterMap
