language: python

python: 
  - 3.4

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install binutils libproj-dev gdal-bin python-gdal

install:
  - pip install -r requirements.txt

script: 
  - python manage.py test WaldmeisterMap
