language: python

python:
  - "3.6"

env:
  - DJANGO_VERSION=2.0

install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install

script: 
  - python manage.py test WaldmeisterMap
