language: generic

env:
  - DJANGO_VERSION=2.0

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3
  - sudo apt-get build-dep python-gdal

install:
  - sudo pip install -r requirements.txt

script: 
  - python manage.py test WaldmeisterMap
