language: python

python:
  - "3.6"

env:
  - DJANGO_VERSION=2.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gdal

install:
  - pip install -r requirements.txt

script: 
  - python manage.py test WaldmeisterMap
