language: python

python: 
  - 3.4

env:
  global:
  - PGPORT=5433

virtualenv:
  system_site_packages: true

services:
  - postgresql

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install binutils libproj-dev gdal-bin python-gdal

install:
  - pip install -r requirements.txt

before_script:
  - psql -U postgres -c "create extension postgis"

script: 
  - python manage.py test WaldmeisterMap
